### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by NeonDevil** [Dankirk/strictlybetter#19]
I had some minor issues getting Laravel to migrate without errors - namely importing scryfall-default-cards.json into the database.

![scryfall-default-cards](https://user-images.githubusercontent.com/7275372/95162138-d27fb280-0759-11eb-8f28-6644a7c56380.PNG)

**Comment by Dankirk** [comment]
Thanks for reporting this and the revised guidelines. 

I think I will modify the failing migration file, so that if the database is empty it won't run the part where the scryfall file is needed. It's intention is to update existing cards in the database, so with new deployment (no cards in the database yet) it's not needed.

After fixing that, we don't need to manually download the bulk-file either, so we should change the guide accordingly. The bulk-file will be later downloaded with `php artisan full-update`

Another minor issue with the guide is duplication of the steps `composer install ` and `php artisan key:generate` 
If you could fix those, I see no problem with merging.

**Comment by NeonDevil** [comment]
@Dankirk: fixed mentioned issues and added some minor changes. Commits added to patch-1
